name: CI/CD Pipeline
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Build project
        run: mvn clean package

      - name: Print logs
        run: ls target/

      - name: Deploy to Linode
        uses: appleboy/scp-action@master
        with:
          host: 170.187.241.49
          username: vahe-excede
          passphrase: "Njr1011"
          key: ${{ secrets.LINODE_PRIVATE_KEY }}
          source: target/PaymentSystem-0.0.1-SNAPSHOT.jar
          target: /var/www/myapp/myapp.jar
